project:
  type: website
  output-dir: ../dist/blog

website:
  title: "Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: ../index.html
        text: "Academic Portfolio"
      - href: https://scholar.google.com/citations?user=8qSJ1GYAAAAJ
        icon: mortarboard
      - href: https://github.com/qipengchen
        icon: github
      - href: https://www.linkedin.com/in/qipeng-chen-604528271/
        icon: linkedin
  page-footer:
    center:
      - text: "Qipeng Chen"
      - text: "Back to Academic Portfolio"
        href: ../index.html

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: false
    smooth-scroll: true
    link-external-newwindow: true
    favicon: scholar-avatar.jpg 